name: Echo Environment Variables and Secret

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment'
        required: true
        type: choice
        options:
          - production

jobs:
  echo_variables:
    runs-on: ubuntu-latest
    steps:
      - name: echo variable
        run: echo "API_ID is ${{ env.API_ID }}"
      - name: echo secret
        run: echo "API_KEY is ${{ secrets.API_KEY }}"

