name: Echo Environment Variables and Secret

on:
  workflow_dispatch:

jobs:
  echo_variables:
    runs-on: ubuntu-latest
    steps:
      - name: echo variable
        run: echo "API_ID is ${{ vars.API_ID }}"
      - name: echo secret
        run: echo "API_KEY is ${{ secrets.API_KEY }}"

