name: Echo Environment Variables and Secret

on:
  workflow_dispatch:

jobs:
  echo_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Environment Variable is API_ID: $API_ID"
          echo "Environment Secret is API_KEY: $API_KEY"
        env:
          API_ID: ${{ variables.API_ID }}
          API_KEY: ${{ secrets.API_KEY }}
