name: Echo Environment Variables and Secret

on:
  workflow_dispatch:

jobs:
  echo_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environment
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "API_ID: ${{ env.API_ID }}"
          echo "API_KEY: ${{ secrets.API_KEY }}"

